server:
  port: 4000

spring:
  application:
    name: patient-service

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

#  datasource:
#    url: jdbc:postgresql://localhost:5000/patient_service
#    username: admin
#    password: admin123
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
logging:
  level:
    root: info

#springdoc:
#  api-docs:
#    path: /v1/api-docs
#  swagger-ui:
#    path: /swagger-ui
